{{- if .Values.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "microservice.fullname" . }}
  namespace: {{ include "microservice.namespace" $ }}
spec:
  {{- if or .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  {{- if and .Values.pdb.minAvailable .Values.pdb.maxUnavailable }}
  {{ fail "ERROR: Please, use only one of minAvailable or maxUnavailable" }}
  {{- end }}
  {{- end }}  
  selector:
    matchLabels:
      app: {{ template "microservice.fullname" . }}
{{- end }}
