{{- if and .Values.rbac.enabled .Values.rbac.spec -}}
{{ range .Values.rbac.spec }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "microservice.fullname" $ }}-{{ .name }}
  labels:
    {{- include "microservice.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .namespaceOverride }}
  namespace: {{ .namespaceOverride }}
  {{- end }}
rules:
  {{- toYaml .roleRules | nindent 2 }}
{{- end -}}
{{- end -}}
