{{- if and .Values.serviceAccount.enabled .Values.rbac.enabled .Values.rbac.spec }}
{{ range .Values.rbac.spec }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "microservice.fullname" $ }}-{{ .name }}
  labels:
    {{- include "microservice.labels" $ | nindent 4 }}
  {{- with $.Values.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .namespaceOverride }}
  namespace: {{ .namespaceOverride }}
  {{- end }}
roleRef:
  kind: Role
  name: {{ template "microservice.fullname" $ }}-{{ .name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ template "microservice.fullname" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}
