{{- if .Values.secrets }}
{{ range .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" ( include "microservice.fullname" $ ) .name | quote }}
  namespace: {{ include "microservice.namespace" $ }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "microservice.labels" $ | nindent 4 }}
data:
{{- range $key, $val := .data }}
  {{- if hasSuffix "filepath" $key }}
  {{ $key | replace ".filepath" "" }}: {{ $.Files.Get $val | b64enc | quote }}
  {{- else if or (hasSuffix ".crt" $key ) (hasSuffix ".key" $key ) (hasSuffix ".pem" $key ) }}
  {{ $key }}: {{ $val | quote | nindent 4 }}
  {{ else }}
  {{ $key }}: {{ $val | b64enc | quote | nindent 4 }}
  {{- end }}
{{- end }}  
{{- end }}
{{- end }}
