{{- if .Values.dockerConfigJson.enabled }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ template "microservice.fullname" . }}-registry
  namespace: {{ include "microservice.namespace" $ }}
  labels:
    {{- include "microservice.labels" $ | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/resource-policy": "keep"
  {{- with $.Values.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}