apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "microservice.fullname" . }}
  namespace: {{ template "microservice.namespace" .}}
spec:
  type: {{ .Values.service.type }}
  ports: {{- toYaml .Values.service.ports | nindent 4 }}     
  selector:
    app: {{ template "microservice.fullname" . }}
