{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
    annotations:
        {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
