{{- if .Values.virtualServices -}}
{{ range .Values.virtualServices }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" ( include "microservice.fullname" $ ) .name | quote }}
  namespace: {{ include "microservice.namespace" $ }}
  {{- with $.Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: {{- include "microservice.labels" $ | nindent 4 }}
spec: {{- include "microservice.tplvalues.render" (dict "value" .spec "context" $) | nindent 2 }}
{{- end }}
{{- end }}